### PR TITLE
Move plugin to a separate package

### LINKED ISSUE #103: Move Protocols.Plugin to a separate package
Right now, doctests and HLS complain when the `circuit-notation` plugin is used within a file in `clash-protocols`, because the compilation of the plugin is done together with the file. To fix this issue, the plugin, along with all of the definitions it needs, has to be moved to a separate package, for example `clash-protocols-base`. Then, building `clash-protocols` can depend on `clash-protocols-base` and the issue should be resolved.

### PR DESCRIPTION
**Pull request by t-wallet**
Fixes #103

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
Could you move `clash-protocols` to a similarly named folder? Like `clash-compiler` does for its packages. Other than that LGTM.

**Comment by t-wallet** [comment]
> Could you move `clash-protocols` to a similarly named folder? Like `clash-compiler` does for its packages. Other than that LGTM.

Done!

**Review by martijnbastiaan — APPROVED** [review]
Thank you

**Comment by martijnbastiaan** [comment]
Agreed, @t-wallet could you re-export?

**Comment by bgamari** [comment]
Done in #106

**Pull request merged**
